### ISSUE TITLE
Unable to start-failovertest

### ISSUE THREAD

**Issue by taran1392** [ChristopherGLewis/ZertoModule#1]
Hi Christopher,
I am getting the error {"Message":"failed parsing as a valid CheckPoint Identifier"} while trying to start failover test.

Can you help ?

**Comment by ChristopherGLewis** [comment]
How are you executing the command?

**Comment by taran1392** [comment]
I have resolved the issue.Looks like Zerto has made some changes to API. The parameter name 'CheckpointIdentifier ' has been changed to 'CheckpointId' for failovertest API.
