### ISSUE TITLE
Getting Zerto Resource Report - issue with URI

### ISSUE THREAD

**Issue by mtboren** [ChristopherGLewis/ZertoModule#3]
Greetings, @ChristopherGLewis -

Enjoying the module.

As I was starting to leverage the `Get-ZertoResoureReport` and `Get-ZertoResoureReportAdvFilter` cmdlets, though, I came across what may be a bug:  the URI is not valid, at least in the Zerto v5.0 u2 version that I am using -- it seems to be missing an "s".

That is, these two cmdlets are using `/ZvmService/ResourceReport/` in the URI, but per the Zerto API docs for the [Resources Report API](http://s3.amazonaws.com/zertodownload_docs/Latest/Zerto%20Virtual%20Replication%20REST%20APIs%20Online%20Help/index.html#page/Zerto_Virtual_Replication_REST_APIs/StatusAPIs.4.117.html), the URI is `/ZvmService/ResourcesReport/` (notice the "s" in "Resources").

I tested by updating that URI in the function definitions in a copy of the .psm1 file, and, success.

So, I'm opening this GHub issue to track this one.

Thanks for all the work on making this module what it is.  Cheers

**Comment by ChristopherGLewis** [comment]
Thanks - I should have a new module version published today or tomorrow - I'm looking at correcting some of the Zerto Version and deprecated API issues.

**Comment by mtboren** [comment]
Superb!  Thanks much

**Comment by ChristopherGLewis** [comment]
Udpated to version 1.0.3 to fix the ResourcesReport - note that the commands have changed to Get-ZertoResouresReport and Get-ZertoResourcesReportAdvFilter to reflect the actual API call.
