### ISSUE TITLE
Updating JournalHistoryInHours

### ISSUE THREAD

**Issue by prisoner107** [ChristopherGLewis/ZertoModule#5]
Im attempting to update most of my VPG Journal History from 1 Day to 7 Days. 
Also would like to update JournalSizeHardLimit and JournalSizeWarningThreshold disk sizes.
Im sure once I figure out how to change one of these settings, the other will fall into place. 

How would go about creating the ZertoVGPSetting object if I want to just change the JournalHistoryHours in the below example. Of course, my example will not work. 

`$VPGID = Get-ZertoVPGID -VpgName  test01-t

$VPGSettingID = Convert-ZertoVPGToVPGSetting -ZertoVpgIdentifier $VPGID

$TestJournalTime = '168'

Set-ZertoVPGSettingBasic -ZertoVpgSettingsIdentifier $VPGSettingID -ZertoVpgSettingBasic $TestJournalTime`

**Comment by ChristopherGLewis** [comment]
You want to submit your VPGSetting after doing your change:

```$VPGID = Get-ZertoVPGID -VpgName test01-t
$VPGSettingID = Convert-ZertoVPGToVPGSetting -ZertoVpgIdentifier $VPGID
$TestJournalTime = '168'
Set-ZertoVPGSettingBasic -ZertoVpgSettingsIdentifier $VPGSettingID -ZertoVpgSettingBasic $TestJournalTime
Submit-ZertoVPGSetting -ZertoVpgSettingsIdentifier $VPGSettingID
```

The submit command is the equivolent of POSTing a /commit to the VPG.

**Comment by prisoner107** [comment]
Perfect! Thank you.
Was also trying to get around to updating the Journal Limitation time, this worked:

$VPGID = Get-ZertoVPGID -VpgName  test01-t
$VPGSettingID = Convert-ZertoVPGToVPGSetting -ZertoVpgIdentifier $VPGID
$conf = [PSCustomObject]@{
    HardLimitInMB = '1024000'
    WarningThresholdInMB = '1022976'
    WarningThresholdInPercent = '0'
    HardLimitInPercent = '0'
}
$Stuff = New-ZertoVPGSettingJournal -Limitation $conf
Set-ZertoVPGSettingJournal -ZertoVpgSettingsIdentifier $VPGSettingID -ZertoVPGSettingJournal $Stuff
Submit-ZertoVPGSetting -ZertoVpgSettingsIdentifier $VPGSettingID

**Comment by prisoner107** [comment]
Perfect! thank you.
Was also trying to work around updating the JournalLimitation Setting, the below code worked:
```$VPGID = Get-ZertoVPGID -VpgName  test01-t
$VPGSettingID = Convert-ZertoVPGToVPGSetting -ZertoVpgIdentifier $VPGID
$conf = [PSCustomObject]@{
    HardLimitInMB = '1024000'
    WarningThresholdInMB = '1022976'
    WarningThresholdInPercent = '0'
    HardLimitInPercent = '0'
}
$Stuff = New-ZertoVPGSettingJournal -Limitation $conf
Set-ZertoVPGSettingJournal -ZertoVpgSettingsIdentifier $VPGSettingID -ZertoVPGSettingJournal $Stuff
Submit-ZertoVPGSetting -ZertoVpgSettingsIdentifier $VPGSettingID 
```
